CREATE TABLE system (
    UUID uuid NOT NULL DEFAULT gen_random_uuid(),
    AuthorAccountUUID uuid NOT NULL,
    TimestampCreated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    CPUPartUUID uuid NOT NULL,
    CPUCount integer NOT NULL,
    CPUCoolerPartUUID uuid NOT NULL,
    MotherboardPartUUID uuid NOT NULL,
    RAMPartUUID uuid NOT NULL,
    RAMCount integer NOT NULL,
    GPUPartUUID uuid NOT NULL,
    GPUCount integer NOT NULL,
    StoragePartUUID uuid NOT NULL,
    SystemRAIDUUID uuid NOT NULL,
    PowerSupplyPartUUID uuid NOT NULL,
    ChassisPartUUID uuid NOT NULL,
    PRIMARY KEY (UUID),
    FOREIGN KEY (CPUPartUUID) REFERENCES cpu(PartUUID),
    CONSTRAINT system_cpucount_range CHECK (CPUCount > 0 AND CPUCount <= 4),
    FOREIGN KEY (CPUCoolerPartUUID) REFERENCES cpucooler(PartUUID),
    FOREIGN KEY (MotherboardPartUUID) REFERENCES motherboard(PartUUID),
    FOREIGN KEY (RAMPartUUID) REFERENCES ram(PartUUID),
    CONSTRAINT system_ramcount_range CHECK (RAMCount > 0 AND RAMCount <= 32),
    FOREIGN KEY (GPUPartUUID) REFERENCES gpu(PartUUID),
    CONSTRAINT system_gpucount_range CHECK (GPUCount > 0 AND GPUCount <= 8),
    FOREIGN KEY (StoragePartUUID) REFERENCES storage(PartUUID),
    FOREIGN KEY (SystemRAIDUUID) REFERENCES systemraid(UUID),
    FOREIGN KEY (PowerSupplyPartUUID) REFERENCES powersupply(PartUUID),
    FOREIGN KEY (ChassisPartUUID) REFERENCES chassis(PartUUID)
);