CREATE TABLE part (
	Id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	CreatedTimestamp timestamptz NOT NULL DEFAULT transaction_timestamp(),
	Manufacturer varchar(50) NOT NULL,
	Model varchar(50) NOT NULL,
	ShortDescription varchar(100) NOT NULL GENERATED ALWAYS AS (Manufacturer || ' ' || Model) STORED,
	LongDescription varchar(200) NULL,
	Price numeric NOT NULL CHECK (Price >= 0 AND Price <= 100000)
);