CREATE TABLE chipset (
	Id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Manufacturer varchar(30) NOT NULL,
	Version varchar(10) NOT NULL,
	MotherboardSocketId integer NOT NULL REFERENCES motherboardsocket(Id)
);