CREATE TABLE fan (
    UUID uuid NOT NULL,
    FanDiameterUUID uuid NOT NULL,
    WidthMM integer NOT NULL,
    PWMSupport boolean NOT NULL,
    MinRPM integer NOT NULL,
    MaxRPM integer NOT NULL,
    MinAirflow real NOT NULL,
    MaxAirflow real NOT NULL,
    MinStaticPressure real NOT NULL,
    MaxStaticPressure real NOT NULL,
    MinAcousticOutput real NOT NULL,
    MaxAcousticOutput real NOT NULL,
    FanVoltageUUID uuid NOT NULL,
    MaxCurrent real NOT NULL,
    MTBFHours integer NOT NULL,
    PRIMARY KEY (UUID),
    FOREIGN KEY (UUID) REFERENCES part(UUID),
    FOREIGN KEY (FanDiameterUUID) REFERENCES fandiameter(UUID),
    CONSTRAINT fan_width_range CHECK (WidthMM >= 15 AND WidthMM <= 25),
    CONSTRAINT fan_minimumrpm_range CHECK (MinRPM >= 400 AND MinRPM <= 30000),
    CONSTRAINT fan_maximumrpm_range CHECK (MaxRPM >= MinRPM AND MaxRPM <= 40000),
    CONSTRAINT fan_minairflow_range CHECK (MinAirflow > 0 AND MinAirflow <= 400),
    CONSTRAINT fan_maxairflow_range CHECK (MaxAirflow >= MinAirflow AND MaxAirflow <= 600),
    CONSTRAINT fan_minstaticpressure_range CHECK (MinStaticPressure > 0 AND MinStaticPressure <= 250),
    CONSTRAINT fan_maxstaticpressure_range CHECK (MaxStaticPressure >= MinStaticPressure AND MaxStaticPressure <= 500),
    CONSTRAINT fan_minacousticoutput_range CHECK (MinAcousticOutput > 0 AND MinAcousticOutput <= 80),
    CONSTRAINT fan_maxacousticoutput_range CHECK (MaxAcousticOutput >= MinAcousticOutput AND MaxAcousticOutput <= 100),
    FOREIGN KEY (FanVoltageUUID) REFERENCES fanvoltage(UUID),
    CONSTRAINT fan_maximumcurrent_range CHECK (MaxCurrent > 0 AND MaxCurrent <= 10),
    CONSTRAINT fan_mtbfhours_range CHECK (MTBFHours > 0 AND MTBFHours <= 2000000)
);