CREATE TABLE storage (
    PartUUID uuid NOT NULL,
    CapcityGBytes integer NOT NULL,
    ReadBandwidth integer NOT NULL,
    WriteBandwidth integer NOT NULL,
    ReadIOPS integer NULL,
    WriteIOPS integer NULL,
    MTBF integer NULL,
    MaxTBW integer NULL,
    CacheSizeMBytes integer NULL,
    PRIMARY KEY (PartUUID),
    FOREIGN KEY (PartUUID) REFERENCES part(UUID),
    CONSTRAINT storage_capacity_range CHECK (CapcityGBytes > 16 AND CapcityGBytes <= 40000),
    CONSTRAINT storage_readbandwidth_range CHECK (ReadBandwidth > 0 AND ReadBandwidth <= 14000),
    CONSTRAINT storage_writebandwidth_range CHECK (WriteBandwidth > 0 AND WriteBandwidth <= 14000),
    CONSTRAINT storage_readiops_range CHECK (ReadIOPS > 0 AND ReadIOPS <= 2000000),
    CONSTRAINT storage_writeiops_range CHECK (WriteIOPS > 0 AND WriteIOPS <= 2000000),
    CONSTRAINT storage_mtbf_range CHECK (MTBF > 0 AND MTBF <= 4000000),
    CONSTRAINT storage_maxtbw_range CHECK (MaxTBW > 0 AND MaxTBW <= 20000),
    CONSTRAINT storage_cachesizembytes_range CHECK (CacheSizeMBytes > 0 AND CacheSizeMBytes <= 5000)
);